name: GitHub Actions Security Analysis with zizmor 🌈

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  zizmor:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run zizmor 🌈
        run: pipx run --spec 'zizmor==1.29.0' zizmor --format=github --no-exit-codes .
        env:
          GH_TOKEN: ${{ github.token }}
