name: GitHub Actions Security Analysis with zizmor 🌈

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  zizmor:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run zizmor 🌈
        run: pipx run --spec 'zizmor==1.29.0' zizmor --format=sarif . > zizmor.sarif
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@b96794f015dfd88f77b49b1c93e0fa7110f94c63 # v4.38.0
        with:
          sarif_file: zizmor.sarif
          category: zizmor
